name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [macos-latest]

    steps:
      - name: STEP 1. Checkout repository
        uses: actions/checkout@v2

      - name: STEP 2. Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: STEP 3. Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel pytest
          brew install boost boost-python3

      - name: STEP 4. Set up Pyenv
        uses: gabrielfalcao/pyenv-action@v6
        with:
          default: 3.7.6
          versions: 2.7.17
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: STEP 5. Build wheel
        run: |
          pyenv local 2.7.17
          python setup.py v8
          pyenv local system
          sudo python setup.py sdist bdist_wheel -d ${{ github.workspace }}/wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}
          sudo python setup.py install
          pytest
        env:
          STPYV8_BOOST_PYTHON: boost_python38

      - name: STEP 6. Upload wheel
        uses: actions/upload-artifact@v1
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            ${{ github.workspace }}/wheelhouse-${{ matrix.os }}-${{ matrix.python-version }}
            v8/out.gn/x64.release.sample/icudtl.dat
