name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        python-version: [3.9]

    steps:
      - name: STEP 1. Checkout repository
        uses: actions/checkout@v2

      - name: STEP 2. Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: STEP 3. Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel pytest
          brew install boost boost-python3

      - name: STEP 4. Set up Pyenv
        uses: gabrielfalcao/pyenv-action@v6
        with:
          default: 3.7.6
          versions: 2.7.17
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: STEP 5. Build wheel
        run: |
          pyenv local 2.7.17
          python setup.py v8
          pyenv local system
          sudo python setup.py sdist bdist_wheel -d stpyv8-${{ matrix.os }}-${{ matrix.python-version }}
          sudo python setup.py install
          sudo cp v8/out.gn/x64.release.sample/icudtl.dat stpyv8-${{ matrix.os }}-${{ matrix.python-version }}/icudtl.dat

      - name: STEP 6. Test wheel
        run: |
          pytest -v

      - name: STEP 7. Create wheel zip
        uses: papeloto/action-zip@v1
        with:
          files: stpyv8-${{ matrix.os }}-${{ matrix.python-version }}/
          recursive: false
          dest: stpyv8-${{ matrix.os }}-python-${{ matrix.python-version }}.zip

      - name: STEP 8. Upload wheel zip
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: stpyv8-${{ matrix.os }}-python-${{ matrix.python-version }}.zip
