name: Build

on:
  release:
    types: [published]
    branches:
      - master

jobs:
  build:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12]
        python-version: ['3.11']

    steps:
      - name: STEP 1. Checkout repository
        uses: actions/checkout@v3

      - name: STEP 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: STEP 3. Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel pytest
          brew update
          brew install boost
          # The option --ignore-dependencies is a workaround required to
          # avoid boost-python3 installing python@3.11. This option will
          # be removed when Python default Mac OSX version will be v3.11
          brew install boost-python3 --ignore-dependencies
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

      - name: STEP 4. Build wheel
        run: |
          python setup.py v8
          sudo --preserve-env=STPYV8_DEBUG python setup.py sdist bdist_wheel -d stpyv8-${{ matrix.os }}-${{ matrix.python-version }}-debug
          sudo --preserve-env=STPYV8_DEBUG python setup.py install
          sudo --preserve-env=STPYV8_DEBUG cp v8/out.gn/x64.release.sample/icudtl.dat stpyv8-${{ matrix.os }}-${{ matrix.python-version }}-debug/icudtl.dat
        env:
          STPYV8_DEBUG: 1

      - name: STEP 5. Test wheel
        run: |
          pytest -v

      - name: STEP 6. Create wheel zip
        uses: vimtor/action-zip@v1.1
        with:
          files: stpyv8-${{ matrix.os }}-${{ matrix.python-version }}-debug/
          recursive: false
          dest: stpyv8-${{ matrix.os }}-python-${{ matrix.python-version }}-debug.zip

      - name: STEP 7. Upload to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'stpyv8-${{ matrix.os }}-python-${{ matrix.python-version }}-debug.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
