name: Build

on:
  release:
    types: [published]
    branches:
      - master

jobs:
  build:
    name: Build wheel on ${{ matrix.os }}
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.9]
        os: [macos-latest]

    steps:
      - name: STEP 1. Checkout repository
        uses: actions/checkout@v2

      - name: STEP 2. Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: STEP 3. Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel pytest
          brew install boost boost-python3

      - name: STEP 4. Set up Pyenv
        uses: gabrielfalcao/pyenv-action@v6
        with:
          default: 3.7.6
          versions: 2.7.17

      - name: STEP 5. Build wheel
        run: |
          pyenv local 2.7.17
          python setup.py v8
          pyenv local system
          sudo python setup.py sdist bdist_wheel -d wheelhouse
          sudo python setup.py install
          pytest -v tests/
        env:
          STPYV8_BOOST_PYTHON: boost_python38

      - name: STEP 6. Upload to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'wheelhouse/*;v8/out.gn/x64.release.sample/icudtl.dat'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
